---
- name: playbook
  become: yes
  become_method: "sudo"
  hosts: fantasy

  tasks:

    - name: Cloning git
      git:
        repo: "https://github.com/alejandrofm98/fantasy-scrapper.git"
        dest: "/home/proyectos/fantasy-scrapper"
        force: true

    - name: Copying .env
      ansible.builtin.copy:
        src: ~/IdeaProjects/fantasy-scrapper/Config-servidores/database/.env
        dest: /home/proyectos/fantasy-scrapper/Config-servidores/database/.env

    - name: Run `docker-compose down`
      community.docker.docker_compose:
        project_src: /home/proyectos/fantasy-scrapper/Config-servidores/database
        state: absent
      register: output


    - name: Run `docker-compose up`
      community.docker.docker_compose:
        project_src: /home/proyectos/fantasy-scrapper/Config-servidores/database
        build: true
      register: output
